name: Delete temp-pr branch after merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-temp-pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'temp-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Delete temp-pr branch from remote
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.PERSONAL_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/temp-pr
