name: Sync from Upstream

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/prashilshah98/prashilshah98.github.io.git
          git fetch upstream

      - name: Merge upstream/main into workspace/main
        run: git merge upstream/main --allow-unrelated-histories || true

      - name: Remove workflows folder (exclude from sync)
        run: |
          rm -rf .github/workflows
          git rm -r --cached .github/workflows || true
          git commit -m "Remove synced .github/workflows" || echo "No changes to commit"

      - name: Push changes to workspace/main
        run: git push origin main
